# -*- coding: utf-8 -*-
__title__ = "Reuse Code in pyRevit"
__doc__ = """Version = 1.0
Date    = 07.07.2025
_____________________________________________________________________
Description:
Learn how to create reusable code with pyRevit.
_____________________________________________________________________
How-to:
-> Click on the button
-> 
-> 
-> 
_____________________________________________________________________
Last update:

- [07.07.2025] - 1.0 RELEASE
_____________________________________________________________________
Author: Douglas Corrêa"""

from stringold import replace

# ╦╔╦╗╔═╗╔═╗╦═╗╔╦╗╔═╗
# ║║║║╠═╝║ ║╠╦╝ ║ ╚═╗
# ╩╩ ╩╩  ╚═╝╩╚═ ╩ ╚═╝ IMPORTS
#==================================================
# Regular + Autodesk
from Autodesk.Revit.DB import *



# ╦  ╦╔═╗╦═╗╦╔═╗╔╗ ╦  ╔═╗╔═╗
# ╚╗╔╝╠═╣╠╦╝║╠═╣╠╩╗║  ║╣ ╚═╗
#  ╚╝ ╩ ╩╩╚═╩╩ ╩╚═╝╩═╝╚═╝╚═╝ VARIABLES
#==================================================
doc   = __revit__.ActiveUIDocument.Document #type: Document
uidoc = __revit__.ActiveUIDocument          #type: UIDocument
app   = __revit__.Application               #Application

# ╔═╗╦ ╦╔╗╔╔═╗╔╦╗╦╔═╗╔╗╔╔═╗
# ╠╣ ║ ║║║║║   ║ ║║ ║║║║╚═╗
# ╚  ╚═╝╝╚╝╚═╝ ╩ ╩╚═╝╝╚╝╚═╝
#==================================================




# ╔╦╗╔═╗╦╔╗╔
# ║║║╠═╣║║║║
# ╩ ╩╩ ╩╩╝╚╝ MAIN
#==================================================
# START CODE HERE

from Snippets._selection import get_select_elements

sel_el = get_select_elements()

sel_walls = get_select_elements([Wall, Floor])

print(sel_el)
print(sel_walls)

